#pragma once

enum IRC_CODES {
	/* Initial replies (001-005) */
	RPL_WELCOME = 001,	 // Welcome message
	RPL_YOURHOST = 002,	 // Your host is...(Probably local lol)
	RPL_CREATED = 003,	 // Server created at...
	RPL_MYINFO = 004,	 // Server info
	RPL_ISUPPORT = 005,	 // Server supports this and that (CAP)

	/* Command replies (200-399) */
	RPL_TRACELINK = 200,		// Trace link
	RPL_TRACECONNECTING = 201,	// Trace connecting
	RPL_TRACEHANDSHAKE = 202,	// Trace handshake
	RPL_TRACEUNKNOWN = 203,		// Trace unknown
	RPL_TRACEOPERATOR = 204,	// Trace operator
	RPL_TRACEUSER = 205,		// Trace user
	RPL_TRACESERVER = 206,		// Trace server
	RPL_STATSLINKINFO = 211,	// Stats link info
	RPL_STATSCOMMANDS = 212,	// Stats commands
	RPL_STATSCLINE = 213,		// Stats C line
	RPL_STATSNLINE = 214,		// Stats N line
	RPL_STATSILINE = 215,		// Stats I line
	RPL_STATSKLINE = 216,		// Stats K line
	RPL_ENDOFSTATS = 219,		// End of stats report
	RPL_UMODEIS = 221,			// User mode is
	RPL_STATSLLINE = 241,		// Stats L line
	RPL_STATSUPTIME = 242,		// Stats uptime
	RPL_STATSOLINE = 243,		// Stats O line
	RPL_LUSERCLIENT = 251,		// Luser client
	RPL_LUSEROP = 252,			// Luser operator count
	RPL_LUSERUNKNOWN = 253,		// Luser unknown connections
	RPL_LUSERCHANNELS = 254,	// Luser channels count
	RPL_LUSERME = 255,			// Luser me
	RPL_ADMINME = 256,			// Admin me
	RPL_ADMINLOC1 = 257,		// Admin location 1
	RPL_ADMINLOC2 = 258,		// Admin location 2
	RPL_ADMINEMAIL = 259,		// Admin email
	RPL_LOCALUSERS = 265,		// Local users
	RPL_GLOBALUSERS = 266,		// Global users
	RPL_AWAY = 301,				// User away message
	RPL_USERHOST = 302,			// User hostnames
	RPL_ISON = 303,				// Users currently online
	RPL_UNAWAY = 305,			// You are no longer marked as away
	RPL_NOWAWAY = 306,			// You have been marked as away
	RPL_WHOISUSER = 311,		// Whois user information
	RPL_WHOISSERVER = 312,		// Whois server information
	RPL_WHOISOPERATOR = 313,	// Whois operator information
	RPL_WHOISIDLE = 317,		// Whois idle time
	RPL_ENDOFWHOIS = 318,		// End of WHOIS list
	RPL_WHOISCHANNELS = 319,	// Whois channels list
	RPL_LISTSTART = 321,		// Channel list start
	RPL_LIST = 322,				// Channel list
	RPL_LISTEND = 323,			// End of channel list
	RPL_CHANNELMODEIS = 324,	// Channel mode is
	RPL_CREATIONTIME = 329,		// Channel creation time
	RPL_NOTOPIC = 331,			// No topic set
	RPL_TOPIC = 332,			// Topic for the channel
	RPL_INVITING = 341,			// Invitation sent
	RPL_SUMMONING = 342,		// Summoning user
	RPL_INVITELIST = 346,		// Invite list
	RPL_ENDOFINVITELIST = 347,	// End of invite list
	RPL_EXCEPTLIST = 348,		// Exception list
	RPL_ENDOFEXCEPTLIST = 349,	// End of exception list
	RPL_VERSION = 351,			// Version reply
	RPL_WHOREPLY = 352,			// WHO reply
	RPL_NAMREPLY = 353,			// Names list reply
	RPL_LINKS = 364,			// Links list
	RPL_ENDOFLINKS = 365,		// End of links list
	RPL_ENDOFNAMES = 366,		// End of names list
	RPL_BANLIST = 367,			// Ban list
	RPL_ENDOFBANLIST = 368,		// End of ban list
	RPL_ENDOFWHOWAS = 369,		// End of WHOWAS
	RPL_INFO = 371,				// Information
	RPL_MOTD = 372,				// Message of the day (MOTD)
	RPL_ENDOFINFO = 374,		// End of INFO list
	RPL_MOTDSTART = 375,		// MOTD start
	RPL_ENDOFMOTD = 376,		// End of MOTD
	RPL_YOUREOPER = 381,		// You are now an IRC operator
	RPL_REHASHING = 382,		// Rehashing the server
	RPL_TIME = 391,				// Server time

	/* Error replies (400-599) */
	ERR_UNKNOWNERROR = 400,		 // Unknown error
	ERR_NOSUCHNICK = 401,		 // Nickname not found
	ERR_NOSUCHSERVER = 402,		 // No such server
	ERR_NOSUCHCHANNEL = 403,	 // No such channel
	ERR_CANNOTSENDTOCHAN = 404,	 // Cannot send to channel
	ERR_TOOMANYCHANNELS = 405,	 // Too many channels
	ERR_WASNOSUCHNICK = 406,	 // Nickname not found
	ERR_TOOMANYTARGETS = 407,	 // Too many targets
	ERR_NOORIGIN = 409,			 // No origin specified
	ERR_NORECIPIENT = 411,		 // No recipient specified
	ERR_NOTEXTTOSEND = 412,		 // No text to send
	ERR_NOTOPLEVEL = 413,		 // No top level domain
	ERR_WILDTOPLEVEL = 414,		 // Wildcard in top level domain
	ERR_UNKNOWNCOMMAND = 421,	 // Unknown command
	ERR_NOMOTD = 422,			 // No MOTD file
	ERR_NOADMININFO = 423,		 // No admin info
	ERR_FILEERROR = 424,		 // File error
	ERR_NONICKNAMEGIVEN = 431,	 // No nickname given
	ERR_ERRONEUSNICKNAME = 432,	 // Erroneous nickname
	ERR_NICKNAMEINUSE = 433,	 // Nickname in use
	ERR_NICKCOLLISION = 436,	 // Nickname collision
	ERR_USERNOTINCHANNEL = 441,	 // User not in channel
	ERR_NOTONCHANNEL = 442,		 // Not on channel
	ERR_USERONCHANNEL = 443,	 // User is already on channel
	ERR_NOLOGIN = 444,			 // No login
	ERR_SUMMONDISABLED = 445,	 // Summon disabled
	ERR_USERSDISABLED = 446,	 // Users disabled
	ERR_NOTREGISTERED = 451,	 // Not registered
	ERR_NEEDMOREPARAMS = 461,	 // Need more parameters
	ERR_ALREADYREGISTRED = 462,	 // Already registered
	ERR_NOPERMFORHOST = 463,	 // No permission for host
	ERR_PASSWDMISMATCH = 464,	 // Password mismatch
	ERR_YOUREBANNEDCREEP = 465,	 // You're banned
	ERR_KEYSET = 467,			 // Key set
	ERR_CHANNELISFULL = 471,	 // Channel is full
	ERR_UNKNOWNMODE = 472,		 // Unknown mode
	ERR_INVITEONLYCHAN = 473,	 // Invite only channel
	ERR_BANNEDFROMCHAN = 474,	 // Banned from channel
	ERR_BADCHANNELKEY = 475,	 // Bad channel key
	ERR_NOPRIVILEGES = 481,		 // No privileges
	ERR_CHANOPRIVSNEEDED = 482,	 // Channel operator privileges needed
	ERR_CANTKILLSERVER = 483,	 // Can't kill server
	ERR_RESTRICTED = 484,		 // Restricted
	ERR_UNIQOPRIVSNEEDED = 485,	 // Unique operator privileges needed
	ERR_UMODEUNKNOWNFLAG = 501,	 // Unknown user mode flag
	ERR_USERSDONTMATCH = 502,	 // Users don't match
};
